language: node_js
node_js:
- '0.10'
deploy:
  provider: s3
  access_key_id:
    secure: "V3JKBcYrJA+nsK+eD3X8NzKsXhFQUuEU5qSMw/aHKN5HTTf21rpGIekKgu5F5cdBh/Szzxl/J03xOHlVjIm+56c/wqo1cZ/0hKI4MM+LNqrj+gVYs16/yWV3XDV+FWBLP9ZymGPuf3OyxgDxmMIWcKdVef7V3nOom5T5ImysYWOZOO76PTY3mfyU20ZbQNa19BLpYmKmtIvuoX1VrRoTaZt6ZPSBNbhwNDT4WIo1y5Lxqp3sP3NRSblCVNUx0k9+FQuDKXvWwTUhP/wYnFb98jP27ygWckYzo4gWHEh6NSFcbbRV6ZhNmw8oTW1/uf5JErDwa0QSDnyvH9ufD2Jtjntl1w171jMMi8Rzi9WDuhH2Q3e3XcsB9kXN2cgZx5I141qWk/cECDuSmy2Vwf1XcwfUgGsuEdnyIRvkV2Lw2F6XsEvP3LUi9QdSRxLkusviU1k3VvrIdZ0e647yvDwQzjfJXtvX+CsH+hMKkJmgVHJovzgJVLqpNBuNR+qNu3nI04l/E15gNy/XWxZUQjVy18OlLJxPvAQc8lUAsVsd6bu3mA4TPI4v0P2yGY7uxdrsVLCKGqpOkMIthZabWOfp6BdBfhYaumFml1CEM8aZifVjHc6v3dV5HGhw7j6r9pty2gCRmvspraTTgtQ6OpinUIPGZ0ysKsyqg0esvnoe5NA="
  secret_access_key:
    secure: "jL4AyWOw+dc3H3zsJtWuR+QApLFFnsT7+jaIm1Ocb5LxUyb4NWvqzmMDLFWIPdayp20Bz0GLaWOnTkjDIryd9hHUvDuxZU9HmH+EQNz0HVtFIPMU0FM7H4aIg1PapjUPWydRMn0oPEXV39+uF+IY2lrb2kk7cifIUq0f/8el3i287QbTm6DRIWFHw38JhUqiT9inTm9gVeNUVZzWyI+YTmnQogpu/flZUokGJr7Ocf58D6aB6/0tZ93Z0DZ1WvCoiRh6L3HMOSJaNZIJh9wiRq6/vlLVUfSusWP5fJBD3KKQXmLK8Zjqxi2LklQJD0kqXydjcvmnwFvDpBLLFjOE9V81ShXoX/zWURJmMwiBoDelwpehW+ze7S1YUJwH9y4P8jhnUt3yHQuABrD090VR3Pp7BzAtaCVqkdegwkOtlScZLD4IAQaDaUXh55jnLsnAbou3iWdCglsXoaMRlQWDs5fn6ff0vmO5j9aLJT3sI0wZEDeFNcn7kpQKXkrmGbBdf7yOHkkYws/LLrrQd+5IF74H3xE7oFghS8YeZUpYRTsn04KREP+X7lX8xQK4R6t4aiol8s4tdEwjuk6Pu4GNDqcSPh9njB08IejQuURLbWH5V9I1rbTjIJAtf47PRIoy1ljU1FXBk7sUnkCI6+dqeZ6z/6r0Hwt2iMe5oE08Drs="
  bucket: slide.chatbox-inc.com
  region: Tokyo
  endpoint: s3-website-ap-northeast-1.amazonaws.com
  local-dir: build
  on:
    branch: master